### ISSUE TITLE
Always output: Error: could not find clang++

### ISSUE THREAD

**Issue by seamaner** [rdnetto/YCM-Generator#31] opened 2015-10-27 05:13 UTC
when clang and clang++ are in the save directory and there is a word 'clang' in the path, there is always error like 'could not find clang++...'.

**Comment by rdnetto** [comment] 2015-10-30 03:21
This is a duplicate of #21, which has been fixed on the development branch. I'm merging it into stable now, so updating to the latest version should fix it.

**Closed as completed by rdnetto** 2015-10-30 03:21 UTC
