### ISSUE TITLE
ERROR: No commands were logged to the build log when clang is not installed

### ISSUE THREAD

**Issue by kwkelly** [rdnetto/YCM-Generator#3] opened 2015-04-02 18:57 UTC
It also says:
Your build system may not be compatible.

I'm using cmake to build my project. Cmake configures fine and then using make the build succeeds. However, YCM-Generator can not produce any output. I tried this on two different machines. 

Sorry for the lack of info, but I'm not sure how to get any more debug info from the program.

**Comment by rdnetto** [comment] 2015-04-04 07:25
I've pushed a newer version to the develop branch which supports a --verbose flag for displaying build/configure output - try using that.

**Comment by crdamian** [comment] 2015-04-05 11:16
I'm also seeing this. The output with --verbose flag looks like this:
```
$ python ~/.vim/bundle/YCM-Generator/config_gen.py --verbose .
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Check for working C compiler: /home/crd/.vim/bundle/YCM-Generator/fake-toolchain/Unix/clang
-- Check for working C compiler: /home/crd/.vim/bundle/YCM-Generator/fake-toolchain/Unix/clang -- broken
CMake Error at /usr/share/cmake-2.8/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler
  "/home/crd/.vim/bundle/YCM-Generator/fake-toolchain/Unix/clang" is not able
  to compile a simple test program.

  It fails with the following output:

   Change Dir: /tmp/tmpYT706i/CMakeFiles/CMakeTmp

  

  Run Build Command:/usr/bin/make "cmTryCompileExec1086366954/fast"

  /usr/bin/make -f CMakeFiles/cmTryCompileExec1086366954.dir/build.make
  CMakeFiles/cmTryCompileExec1086366954.dir/build

  make[1]: Entering directory '/tmp/tmpYT706i/CMakeFiles/CMakeTmp'

  /usr/bin/cmake -E cmake_progress_report
  /tmp/tmpYT706i/CMakeFiles/CMakeTmp/CMakeFiles 1

  Building C object
  CMakeFiles/cmTryCompileExec1086366954.dir/testCCompiler.c.o

  /home/crd/.vim/bundle/YCM-Generator/fake-toolchain/Unix/clang -o
  CMakeFiles/cmTryCompileExec1086366954.dir/testCCompiler.c.o -c
  /tmp/tmpYT706i/CMakeFiles/CMakeTmp/testCCompiler.c

  /home/crd/.vim/bundle/YCM-Generator/fake-toolchain/Unix/clang: line 5:
  /usr/bin/clang: No such file or directory

  CMakeFiles/cmTryCompileExec1086366954.dir/build.make:57: recipe for target
  'CMakeFiles/cmTryCompileExec1086366954.dir/testCCompiler.c.o' failed

  make[1]: *** [CMakeFiles/cmTryCompileExec1086366954.dir/testCCompiler.c.o]
  Error 127

  make[1]: Leaving directory '/tmp/tmpYT706i/CMakeFiles/CMakeTmp'

  Makefile:114: recipe for target 'cmTryCompileExec1086366954/fast' failed

  make: *** [cmTryCompileExec1086366954/fast] Error 2

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)


-- Configuring incomplete, errors occurred!
See also "/tmp/tmpYT706i/CMakeFiles/CMakeOutput.log".
See also "/tmp/tmpYT706i/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
Running cmake in '/tmp/tmpYT706i'...

Running make...

Cleaning up...
Build completed in 0.06 sec
ERROR: No commands were logged to the build log (/tmp/tmp9nIKsJ).
Your build system may not be compatible.
```

**Comment by crdamian** [comment] 2015-04-05 11:48
Ok, I took a look at YCM-Generator files and it seems that the problem is that we don't have clang.

**Comment by rdnetto** [comment] 2015-04-05 13:06
Yes, clang is required for cmake and autotools, as they run the compiler to determine what features/quirks it has and what flags to use. I'll add a note to the readme to make the dependency explicit.

@kwkelly Can you confirm that installing clang fixes the problem?

**Comment by crdamian** [comment] 2015-04-05 14:37
Shouldn't it be possible to use any other compiler, e.g. gcc, instead of clang? I've tried that but apparently gcc can't handle compiling CMake CMakeCCompilerId.c with -Aa flag, which seems weird.

**Comment by rdnetto** [comment] 2015-04-05 15:01
In a nutshell, no.

GCC and Clang have different formats for some (many?) of their flags. If we use GCC during the configuration stage, then the flags we collect in the next stage will be in GCC-format, and putting them into the config file will break YCM. (To be specific, it breaks it in such a way that you don't know this is the issue, or which flag is causing problems. I ran into this problem during development, which is why I added that pass-through mode in the first place.)

At any rate, this only affects config file generation - once that's done, you can use whatever compiler you want. (Though YCM will flag any syntax clang doesn't understand as an error.)

**Comment by crdamian** [comment] 2015-04-05 15:07
That's a bit sad for those of us who use gcc instead of clang, but I guess it makes sense since YCM uses clang for completion. Thank you for detailed response!

**Comment by michael-younkin** [comment] 2015-04-05 16:06
I was also having this issue, but downgrading to clang 3.4 (clang 3.5 on Ubuntu 14.04 is called `clang-3.5` and `clang++-3.5`) fixed it.

**Comment by rdnetto** [comment] 2015-04-05 16:30
> That's a bit sad for those of us who use gcc instead of clang, but I guess it makes sense since YCM uses clang for completion. Thank you for detailed response!

No problem. :)

> I was also having this issue, but downgrading to clang 3.4 (clang 3.5 on Ubuntu 14.04 is called clang-3.5 and clang++-3.5) fixed it.

Ah, that explains it. The version in master uses the hardcoded path ```/usr/bin/clang```, and the current development version searches PATH for any executable called ```clang```. You can get it working with clang 3.5 by creating a symlink somewhere in your path for ```clang```. (I'm not particularly inclined to code around a bad default in Ubuntu - IMO, you should always have a clang executable if you have any version of it installed.)

**Comment by kwkelly** [comment] 2015-04-05 22:15
@rdnetto,

I don't have privileges on the machine I'm trying to run YCM-Generator on, so installing clang is kind of a pain. Furthermore, I need OpenMP support, so I can't use clang anyway.

**Comment by rdnetto** [comment] 2015-04-06 07:30
You don't need to use clang for actual compilation, just for generating the config. It doesn't matter that Clang lacks OpenMP support, it's just to collect the flags it would be called with.
You can work around the lack of root privileges like so:

    mkdir ~/bin
    cd bin && ln -s /usr/bin/clang-3.5 clang
    export PATH=$HOME/bin:$PATH

**Comment by michael-younkin** [comment] 2015-04-06 17:27
@rdnetto I agree. You may want to put a note about having clang in your path in the README though, since many people might set `CXX=clang++-3.5` in their environment and assume everything will just work. Also note that this is for Ubuntu 14.04, which is still officially supported until 2019.

**Comment by dongli** [comment] 2015-04-07 07:02
I also face this problem, and I have tried the `develop` branch, but there is no `--verbose` option.

**Comment by rdnetto** [comment] 2015-04-08 12:30
Hmmm, on second thoughts it's probably better to just add a flag to specify the path to clang. Although Ubuntu's design is broken, there are legitimate use cases involving multiple compilers. Besides, we've already got one for make, and that's a much less common issue (it exists purely for the BSDs).

@dongli Did you remember to run ```git pull```? The command is definitely there - if you use ```--help``` it should be listed. Also, make sure you're using it before the project directory path, not after.

**Closed** 2015-04-08 13:06 UTC

**Comment by kjeremy** [comment] 2015-04-10 20:01
I'm still getting this even when specifying --compiler.  This is with a fresh vundle install.

**Comment by rdnetto** [comment] 2015-04-11 01:56
> I'm still getting this even when specifying --compiler. This is with a fresh vundle install.

When using the latest master, do you get an error if you don't specify --compiler? If not, it's a separate bug (and should be reported under a new issue accordingly). Also, please check the output with --verbose to make sure it's not actually compiling the project.
